baseurl = "/"
publishDir = "docs"
title = "erst"
author = "Erik Stenberg"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "erst"

[[menu.main]]
    name = "Stack"
    url = "https://stackoverflow.com/users/7520285/shitoushan"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/shitoushan"
    weight = 2

[[menu.main]]
    name = "Resume"
    url = "http://nbviewer.jupyter.org/github/shitoushan/blog/blob/master/files/CV.pdf"
    weight = 3
